### ISSUE TITLE
Whatsapp crash while sending video

### ISSUE THREAD

**Issue by inFiniTyzZ** [CyanogenMod/android_device_motorola_titan#1]
I use CM12 official for titan. Latest Update

Whatsapp is crashing if I will send a video.

**Comment by luca020400** [comment]
Works fine on latest build
Anyway you should use JIRA for report any kind of bug/problem

**Comment by inFiniTyzZ** [comment]
Yes, but it don't work for me with latest version(should I reinstall whatsapp?)

JIRA is for stable version only? Or not, anyone told me that its not for nightlies :(

**Comment by luca020400** [comment]
For nightlies too but seems titan haven't the jira page right now
I tested and it worked

**Comment by inFiniTyzZ** [comment]
Hmm ok, I mean self recorded videos, not generic vids

**Comment by inFiniTyzZ** [comment]
update: works now, I had done a clean flash of CM, also no error sry :D
